language: python
python:
  - 3.6
  - 3.7
  - 3.8

before_install:
- pip install poetry

install:
- poetry install

script:
- poetry run flake8 roll test
- poetry run coverage run --source roll -m pytest

after_success: codecov
